### ISSUE TITLE
You must supply options.input to rollup

### ISSUE THREAD

**Issue by weypro** [DcBD/vite-hugo-plugin#5]
When I try to apply the plugin in a new hugo project `quickstart`, I get this error `You must supply options.input to rollup`.

The tutorial: https://medium.com/gumgum-tech/faster-development-experience-with-vite-hugo-and-preact-c08cbcfce5fb
Packages:
```
    "@preact/preset-vite": "^2.4.0",
    "npm-run-all": "^4.1.5",
    "onchange": "^7.1.0",
    "typescript": "^4.8.4",
    "vite": "^3.1.4",
    "vite-hugo-plugin": "^3.0.5"
```

**Comment by weypro** [comment]
The solution is here: #6

**Comment by dawidprosba** [comment]
Thanks for the PR, I haven't tested it on windows!! Great job!!
I'll release this fix on monday to npm

**Comment by weypro** [comment]
By the way, if you want to run the vite dev server on Windows following the tutorial mentioned above, it may not work because the plugin `onchange` isn't correctly configured.
Reference: https://github.com/Qard/onchange#usage

The correct command in package.json
```
    "dev:hugo-watch": "onchange \"content/**/*.md\" \"config.toml\" \"layouts/**/*\" -- npm run build:hugo",
```
