### ISSUE TITLE
not compatible with recent hugo configuration changes

### ISSUE THREAD

**Issue by lschierer** [DcBD/vite-hugo-plugin#8]
Hugo recently changed the main configuration file from config.toml to hugo.toml see the [v0.110.0](https://github.com/gohugoio/hugo/releases/tag/v0.110.0) release notes. Please make the plugin work with the new filename.  Thanks!!

**Comment by dawidprosba** [comment]
Added `hugoConfigFileName` property to the plugin configuration where you can set the name of the config file. By default it uses `hugo.toml`.

More info in this [pull request](https://github.com/DcBD/vite-hugo-plugin/pull/9)

CC: @lschierer
